version: '3.8'

services:
  phpfpm:
    build:
      context: .
      dockerfile: ./docker/phpfpm/Dockerfile
    volumes:
      - ./src:/src
    ports:
      - '8000:8000'

  node:
    image: node:14.10.0-alpine3.10
    volumes:
      - ./src:/src

  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./docker/nginx/nginx.conf.d:/etc/nginx/nginx.conf.d
    ports:
      - '80:80'
    depends_on:
      - phpfpm
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'

  redis:
    image: redis:6.0.7
    volumes:
      - ./reids:/data
    restart: always

volumes:
  db_data:
