version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/phpfpm/Dockerfile
    volumes:
      - ./src:/src
    ports:
      - '8000:8000'

  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '80:80'
    depends_on:
      - php-fpm
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
