version: '3.8'

services:
  phpfpm:
    build:
      context: .
      dockerfile: ./docker/phpfpm/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./docker/phpfpm/php.ini:/usr/local/etc/php/php.ini
    ports:
      - '9000:9000'

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    tty: true
    image: node:14.10.0-alpine3.10
    volumes:
      - ./src:/src
      - /src/node_modules

  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf
      - ./src:/src
    ports:
      - '80:80'
    depends_on:
      - phpfpm
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'

  redis:
    image: redis:6.0.7
    volumes:
      - ./redis:/data
    restart: always

volumes:
  db_data:
